list: $/nailat/nailat/models/service/columns.yaml
modelClass: Nailat\Nailat\Models\Service
title: Services
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nailat/nailat/services/update/:id'
